### ISSUE TITLE
Conflicts in File Paths After Folder Restructuring

### ISSUE THREAD

**Issue by d11m08y03** [Zahrah26/ComputerShop#19]
#### Description
After recent folder restructuring, the file path for `user_management.c` has become obsolete. This has resulted in compilation errors and broken references in various parts of the codebase that rely on this file.

#### Affected Areas
- The `user_management.c` file has been moved, but the codebase still refers to the old path.
- Any imports or includes relying on the previous file structure are now broken, causing the build process to fail.

**Comment by Zahrah26** [comment]
On it.
